config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  # there may be times when you want to customize the behavior of the belongs_to association reference. Such customizations can easily be accomplished by passing options and scope blocks when you create the association (RoR Guides).

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  validates :content, presence: true
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
      # If you want to render the view that corresponds to a different template within the same controller, you can use render with the name of the view
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to @restaurant
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[index new create]

  def index
    @reviews = Review.where(restaurant_id: @restaurant)
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Mono:wght@400;500;700&display=swap" rel="stylesheet">
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class=container>
  <h1>New Restaurant</h1>

  <%= simple_form_for (@restaurant) do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :address %><br>
      <%= form.text_area :address %>
    </div>

  <div>
      <%= form.label :phone_number %><br>
      <%= form.text_area :phone_number %>
    </div>

  <div>
      <%= form.label :category %><br>
      <%= form.text_area :category %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
  <p><%= link_to "Back to the restaurants", restaurants_path%></p>
</div>

app/views/restaurants/index.html.erb
<div class='container p-4'>
  <nav class="navbar bg-light px-3">
    <h1 class="display-1">Yelp</h1>
  </nav>

  <div class='py-4'>
    <ul class="list-group list-group-flush text-center">
      <% @restaurants.each do |restaurant| %>
      <a href="#" class="list-group-item text-bg-light p-3">
        <%= link_to restaurant.name, restaurant  %>
      </a>
      <% end %>
    </ul>
  </div>

  <div class="p-5 text-end fw-lighter"><%= link_to "Enter a new restaurant", new_restaurant_path%></div>
</div>

app/views/restaurants/new.html.erb
<div class='container p-4'>
  <h1>New Restaurant</h1>

  <%= simple_form_for(@restaurant) do |form| %>
    <div class="mb-3">

      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>

    <div class="mb-3">
      <%= form.label :address %><br>
      <%= form.text_area :address %>
    </div>

    <div class="mb-3">
      <%= form.label :phone_number %><br>
      <%= form.text_area :phone_number %>
    </div>

    <div class="mb-3">
      <%= form.label :category %><br>
      <%= form.text_area :category %>
    </div>

    <div class="mb-3">
      <%= form.submit %>
    </div>
  <% end %>

  <div class="p-5 text-end fw-lighter">
    <p><%= link_to "Back to the restaurants", restaurants_path%></p>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class='container p-4'>

  <div class="m-3">
    <h1 class="my-2"><%= @restaurant.name %></h1>
    <p>Address: <%= @restaurant.address %> </p>
    <p>Phone number:<%= @restaurant.phone_number %></p>
    <p>Category:<%= @restaurant.category %></p>

    <% link_to "Edit this", edit_restaurant_path%>
    <% link_to "Delete this", restaurant_path(@restaurant), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }%>
  </div>
  <div class="m-3 my-5">
    <h2>Reviews</h2>
    <% @restaurant.reviews.each do |review| %>
      <p>
        <strong>Rating:</strong>
        <%= review.rating %>
      </p>

      <p>
        <strong>Content:</strong>
        <%= review.content %>
      </p>
    <% end %>
  </div>

  <div class="m-3 my-5">
    <h2>Add a review:</h2>
    <%= simple_form_for [ @restaurant, @restaurant.reviews.build ] do |form| %>
      <p>
        <%= form.label :rating %><br>
        <%= form.text_field :rating %>
      </p>
      <p>
        <%= form.label :content %><br>
        <%= form.text_area :content %>
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  <div>
  <div class="p-5 text-end fw-lighter">
    <p><%= link_to "Back to the restaurants", restaurants_path%></p>
  </div>
</div>

app/views/reviews/new.html.erb
<div class='contaniner'>
  <%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: [0,1,2,3,4,5] %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
  <% end %>
</div>